# Generated by Django 2.2 on 2019-08-27 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='comentatio',
            new_name='comentario',
        ),
    ]
